-- 20260524150001_seed_pilot_questions_4variants.sql
--
-- PIECE 2: content seed for the 4 per-category pilot variants (D8 revised).
-- Text pulled VERBATIM from Sura's 4 pilot Word docs (NOT retyped). The shared
-- core (Q1-Q4, catch-all, F1-F4) is byte-identical across variants (md5-verified).
--
-- pilot_officials: REPLACE — DELETE the prior 18 seeded questions for that
--   version, then INSERT the current 15 (Q1-Q11 + F1-F4). Safe: 0 responses /
--   0 answers reference them (confirmed).
-- pilot_researchers (16) / pilot_donors (13) / pilot_ngos (13): INSERT into the
--   empty draft variants created by 20260524140002.
--
-- Rules: is_required=true for ALL (Sura's call); is_feedback=true only F1-F4;
-- visible_nationalities='{syrian}' ONLY on officials Q10, NULL elsewhere;
-- order_index sequential (main 1..n, feedback continues); version_id resolved by
-- variant lookup. id left to gen_random_uuid(). questions has NO word_count
-- (that's on answers, D7). Variants stay DRAFT; Sura proofs each before activation.


-- ===== pilot_officials: REPLACE (delete prior 18, insert 15) =====
-- pilot_officials is currently 'active' (seed 0011); the draft-only guard
-- (tg_questions_draft_only) blocks editing questions on an active version. Demote
-- it to 'draft' first so its content can be replaced. Safe: 0 invitations / 0
-- responses reference it. It stays draft (like R/D/N) until Sura proofs the
-- rendered variant; activation of all 4 is a deliberate later step.
UPDATE questionnaire_versions SET status = 'draft' WHERE variant = 'pilot_officials';

DELETE FROM questions
 WHERE version_id = (SELECT id FROM questionnaire_versions WHERE variant = 'pilot_officials');

-- ----- pilot_officials: 15 questions -----
INSERT INTO questions (version_id, question_code, order_index, text_en, text_ar, is_feedback, is_required, visible_nationalities)
SELECT ver.id, d.question_code, d.order_index, d.text_en, d.text_ar, d.is_feedback, TRUE, d.visible_nationalities
FROM (SELECT id FROM questionnaire_versions WHERE variant = 'pilot_officials') AS ver
CROSS JOIN (VALUES
  ('Q1', 1, 'How would you assess the overall performance of the 1987 Yarmouk Agreement in managing the shared water resources of the basin?', 'كيف تُقيّم الأداء العام لاتفاقية اليرموك لعام 1987 في إدارة الموارد المائية المشتركة للحوض؟', FALSE, NULL::nationality_type[]),
  ('Q2', 2, 'The Yarmouk River''s flow has declined significantly over the past decades. In your opinion, what are the main reasons for this decline — and to what extent has this decline affected the river''s ecosystem and surrounding environment?', 'شهد تدفق نهر اليرموك انخفاضاً ملحوظاً خلال العقود الماضية. برأيك، ما هي الأسباب الرئيسية لهذا الانخفاض — وإلى أي مدى أثّر هذا الانخفاض على النظام البيئي للنهر والبيئة المحيطة؟', FALSE, NULL::nationality_type[]),
  ('Q3', 3, 'In light of recent developments in Jordan-Syria relations, should an opportunity arise to revise the current Yarmouk Agreement, what key modifications would you recommend?', 'في ضوء التطورات الأخيرة في العلاقات الأردنية السورية، وفي حال أُتيحت الفرصة لتعديل اتفاقية اليرموك الحالية، ما هي التعديلات الأساسية التي توصي بها؟', FALSE, NULL::nationality_type[]),
  ('Q4', 4, 'The 1987 Agreement focuses entirely on water allocation and does not address environmental protection in any form — such as environmental impact assessment, minimum ecological flows, or water quality standards. How has this absence shaped the environmental condition of the Yarmouk basin over the past four decades — and what specific environmental provisions would you consider essential in any future agreement?', 'تركّز اتفاقية 1987 بالكامل على تخصيص المياه ولا تتناول حماية البيئة بأي شكل — كتقييم الأثر البيئي أو الحد الأدنى للتدفقات البيئية أو معايير جودة المياه. كيف أثّر هذا الغياب على الوضع البيئي لحوض اليرموك خلال العقود الأربعة الماضية — وما هي الأحكام البيئية المحددة التي تعتبرها ضرورية في أي اتفاقية مستقبلية؟', FALSE, NULL::nationality_type[]),
  ('Q5', 5, 'The Agreement covers surface water but does not mention groundwater. Given that the Basalt Aquifer is hydraulically connected to the springs referenced in Article VII, has this gap created problems in managing the basin — and how should groundwater use be addressed in any future agreement?', 'تتناول الاتفاقية المياه السطحية لكنها لا تتطرق للمياه الجوفية. بما أن طبقة البازلت المائية مرتبطة هيدرولوجياً بالينابيع المشار إليها في المادة السابعة، هل تسبّب هذا الغياب بمشاكل في إدارة الحوض — وكيف ينبغي معالجة استخدام المياه الجوفية في أي اتفاقية مستقبلية؟', FALSE, NULL::nationality_type[]),
  ('Q6', 6, 'A joint data-sharing platform has recently been launched for the Yarmouk basin. Does this platform include historical data from previous decades, or only new data going forward? How can the continuity and sustainability of this data collection mechanism be ensured over the long term?', 'تم مؤخراً إطلاق منصة مشتركة لتبادل البيانات حول حوض اليرموك. هل تشمل هذه المنصة البيانات التاريخية من العقود الماضية أم فقط البيانات الجديدة؟ وكيف يمكن ضمان استمرارية آلية جمع البيانات هذه واستدامتها على المدى البعيد؟', FALSE, NULL::nationality_type[]),
  ('Q7', 7, 'The Yarmouk basin is governed by two separate bilateral agreements — the 1987 Agreement between Jordan and Syria, and the 1994 Peace Treaty between Jordan and Israel — each with its own coordination mechanism. In practice, how effective was the Joint Committee established under the 1987 Agreement, and what would you suggest strengthening coordination among all parties in the future?', 'يُدار حوض اليرموك باتفاقيتين ثنائيتين منفصلتين — اتفاقية 1987 بين الأردن وسوريا ومعاهدة السلام لعام 1994 بين الأردن وإسرائيل — لكل منهما آلية تنسيق خاصة. من الناحية العملية، ما مدى فعالية اللجنة المشتركة المنشأة بموجب اتفاقية 1987، وما الذي تقترحه لتعزيز التنسيق بين جميع الأطراف مستقبلاً؟', FALSE, NULL::nationality_type[]),
  ('Q8', 8, 'The agreement''s annex specifies 26 dams, but estimates suggest that significantly more have been built in the basin. Were these additional dams coordinated through the Joint Committee, and how has this additional infrastructure affected the agreement''s implementation and the water balance in the basin?', 'يُحدد ملحق الاتفاقية 26 سداً، لكن التقديرات تشير إلى أن عدداً أكبر بكثير قد أُنشئ في الحوض. هل تم التنسيق بشأنها من خلال اللجنة المشتركة، وكيف أثرت هذه البنية التحتية الإضافية على تنفيذ الاتفاقية والتوازن المائي في الحوض؟', FALSE, NULL::nationality_type[]),
  ('Q9', 9, 'How much water does the Al Wehda Dam actually receive annually compared to its design capacity, and what factors explain this shortfall?', 'كم تبلغ كمية المياه التي يستقبلها سد الوحدة فعلياً سنوياً مقارنةً بسعته التصميمية، وما هي العوامل التي تُفسّر هذا العجز؟', FALSE, NULL::nationality_type[]),
  ('Q10', 10, 'As Syria moves into a new phase of development, how does the government plan to balance agricultural water needs in the Yarmouk basin with the commitments under the bilateral agreement with Jordan?', 'مع دخول سوريا مرحلة جديدة من التنمية، كيف تخطط الحكومة للموازنة بين الاحتياجات المائية الزراعية في حوض اليرموك والالتزامات بموجب الاتفاقية الثنائية مع الأردن؟', FALSE, '{syrian}'::nationality_type[]),
  ('Q11', 11, 'Is there anything else you would like to share regarding the 1987 Agreement, the environmental status of the Yarmouk basin, or the future of transboundary cooperation?', 'هل هناك أي شيء آخر تودّ مشاركته بخصوص اتفاقية 1987، أو الوضع البيئي لحوض اليرموك، أو مستقبل التعاون العابر للحدود؟', FALSE, NULL::nationality_type[]),
  ('F1', 12, 'Were any questions unclear or difficult to understand?', 'هل كانت أي من الأسئلة غير واضحة أو صعبة الفهم؟', TRUE, NULL::nationality_type[]),
  ('F2', 13, 'Were any questions too long?', 'هل كانت أي من الأسئلة طويلة جداً؟', TRUE, NULL::nationality_type[]),
  ('F3', 14, 'Was any important topic missing from the questions?', 'هل كان هناك أي موضوع مهم مفقود من الأسئلة؟', TRUE, NULL::nationality_type[]),
  ('F4', 15, 'How long did it take you to complete all questions?', 'كم من الوقت استغرقت للإجابة على جميع الأسئلة؟', TRUE, NULL::nationality_type[])
) AS d(question_code, order_index, text_en, text_ar, is_feedback, visible_nationalities);

-- ----- pilot_researchers: 16 questions -----
INSERT INTO questions (version_id, question_code, order_index, text_en, text_ar, is_feedback, is_required, visible_nationalities)
SELECT ver.id, d.question_code, d.order_index, d.text_en, d.text_ar, d.is_feedback, TRUE, d.visible_nationalities
FROM (SELECT id FROM questionnaire_versions WHERE variant = 'pilot_researchers') AS ver
CROSS JOIN (VALUES
  ('Q1', 1, 'How would you assess the overall performance of the 1987 Yarmouk Agreement in managing the shared water resources of the basin?', 'كيف تُقيّم الأداء العام لاتفاقية اليرموك لعام 1987 في إدارة الموارد المائية المشتركة للحوض؟', FALSE, NULL::nationality_type[]),
  ('Q2', 2, 'The Yarmouk River''s flow has declined significantly over the past decades. In your opinion, what are the main reasons for this decline — and to what extent has this decline affected the river''s ecosystem and surrounding environment?', 'شهد تدفق نهر اليرموك انخفاضاً ملحوظاً خلال العقود الماضية. برأيك، ما هي الأسباب الرئيسية لهذا الانخفاض — وإلى أي مدى أثّر هذا الانخفاض على النظام البيئي للنهر والبيئة المحيطة؟', FALSE, NULL::nationality_type[]),
  ('Q3', 3, 'In light of recent developments in Jordan-Syria relations, should an opportunity arise to revise the current Yarmouk Agreement, what key modifications would you recommend?', 'في ضوء التطورات الأخيرة في العلاقات الأردنية السورية، وفي حال أُتيحت الفرصة لتعديل اتفاقية اليرموك الحالية، ما هي التعديلات الأساسية التي توصي بها؟', FALSE, NULL::nationality_type[]),
  ('Q4', 4, 'The 1987 Agreement focuses entirely on water allocation and does not address environmental protection in any form — such as environmental impact assessment, minimum ecological flows, or water quality standards. How has this absence shaped the environmental condition of the Yarmouk basin over the past four decades — and what specific environmental provisions would you consider essential in any future agreement?', 'تركّز اتفاقية 1987 بالكامل على تخصيص المياه ولا تتناول حماية البيئة بأي شكل — كتقييم الأثر البيئي أو الحد الأدنى للتدفقات البيئية أو معايير جودة المياه. كيف أثّر هذا الغياب على الوضع البيئي لحوض اليرموك خلال العقود الأربعة الماضية — وما هي الأحكام البيئية المحددة التي تعتبرها ضرورية في أي اتفاقية مستقبلية؟', FALSE, NULL::nationality_type[]),
  ('Q5', 5, 'From a scientific point of view, what is the most equitable method for allocating water from a river whose flow is declining — fixed volumes, percentage-based shares, needs-based allocation, or another approach?', 'من وجهة نظر علمية، ما هي الطريقة الأكثر إنصافاً لتخصيص مياه نهر يستمر تدفقه بالانخفاض — حصص ثابتة، حصص نسبية، تخصيص بناءً على الاحتياجات، أو نهج آخر؟', FALSE, NULL::nationality_type[]),
  ('Q6', 6, 'What is the single most promising method to increase water availability in the basin — aquifer recharge, cloud seeding, wastewater reuse, or something else?', 'ما هي الطريقة الأكثر جدوى لزيادة كمية المياه المتاحة في الحوض — التغذية الاصطناعية للمياه الجوفية، الاستمطار، إعادة استخدام المياه المعالجة، أو غير ذلك؟', FALSE, NULL::nationality_type[]),
  ('Q7', 7, 'Is it scientifically feasible to define a minimum environmental flow that the Yarmouk needs to sustain its ecosystem? If so, what methodology would you recommend, and has any such determination already been attempted?', 'هل من الممكن علمياً تحديد حد أدنى للتدفق البيئي الذي يحتاجه اليرموك للحفاظ على نظامه البيئي؟ وإذا كان ذلك ممكناً، ما هي المنهجية التي توصي بها، وهل جرت أي محاولات لتحديد ذلك سابقاً؟', FALSE, NULL::nationality_type[]),
  ('Q8', 8, 'If both countries distrust each other''s data, what independent monitoring or data collection method would you recommend to build confidence?', 'إذا كان كلا البلدين لا يثقان ببيانات الآخر، ما هي طريقة الرصد أو جمع البيانات المستقلة التي توصي بها لبناء الثقة؟', FALSE, NULL::nationality_type[]),
  ('Q9', 9, 'The 1987 Agreement is often criticized for what it lacks. Is there anything in it worth preserving in a reformed version?', 'كثيراً ما تُنتقد اتفاقية 1987 لما ينقصها. هل هناك شيء فيها يستحق الحفاظ عليه في نسخة مُعدّلة؟', FALSE, NULL::nationality_type[]),
  ('Q10', 10, 'Has the change of government in Syria fundamentally altered the power dynamics over the Yarmouk, or will the same patterns repeat?', 'هل غيّر تغيير الحكم في سوريا موازين القوى حول اليرموك بشكل جوهري، أم أن الأنماط نفسها ستتكرر؟', FALSE, NULL::nationality_type[]),
  ('Q11', 11, 'If you had to design one mechanism to ensure equity in Yarmouk water sharing — just one — what would it be?', 'لو كان عليك تصميم آلية واحدة فقط لضمان العدالة في تقاسم مياه اليرموك — واحدة فقط — ماذا ستكون؟', FALSE, NULL::nationality_type[]),
  ('Q12', 12, 'Is there anything else you would like to share regarding the 1987 Agreement, the environmental status of the Yarmouk basin, or the future of transboundary cooperation?', 'هل هناك أي شيء آخر تودّ مشاركته بخصوص اتفاقية 1987، أو الوضع البيئي لحوض اليرموك، أو مستقبل التعاون العابر للحدود؟', FALSE, NULL::nationality_type[]),
  ('F1', 13, 'Were any questions unclear or difficult to understand?', 'هل كانت أي من الأسئلة غير واضحة أو صعبة الفهم؟', TRUE, NULL::nationality_type[]),
  ('F2', 14, 'Were any questions too long?', 'هل كانت أي من الأسئلة طويلة جداً؟', TRUE, NULL::nationality_type[]),
  ('F3', 15, 'Was any important topic missing from the questions?', 'هل كان هناك أي موضوع مهم مفقود من الأسئلة؟', TRUE, NULL::nationality_type[]),
  ('F4', 16, 'How long did it take you to complete all questions?', 'كم من الوقت استغرقت للإجابة على جميع الأسئلة؟', TRUE, NULL::nationality_type[])
) AS d(question_code, order_index, text_en, text_ar, is_feedback, visible_nationalities);

-- ----- pilot_donors: 13 questions -----
INSERT INTO questions (version_id, question_code, order_index, text_en, text_ar, is_feedback, is_required, visible_nationalities)
SELECT ver.id, d.question_code, d.order_index, d.text_en, d.text_ar, d.is_feedback, TRUE, d.visible_nationalities
FROM (SELECT id FROM questionnaire_versions WHERE variant = 'pilot_donors') AS ver
CROSS JOIN (VALUES
  ('Q1', 1, 'How would you assess the overall performance of the 1987 Yarmouk Agreement in managing the shared water resources of the basin?', 'كيف تُقيّم الأداء العام لاتفاقية اليرموك لعام 1987 في إدارة الموارد المائية المشتركة للحوض؟', FALSE, NULL::nationality_type[]),
  ('Q2', 2, 'The Yarmouk River''s flow has declined significantly over the past decades. In your opinion, what are the main reasons for this decline — and to what extent has this decline affected the river''s ecosystem and surrounding environment?', 'شهد تدفق نهر اليرموك انخفاضاً ملحوظاً خلال العقود الماضية. برأيك، ما هي الأسباب الرئيسية لهذا الانخفاض — وإلى أي مدى أثّر هذا الانخفاض على النظام البيئي للنهر والبيئة المحيطة؟', FALSE, NULL::nationality_type[]),
  ('Q3', 3, 'In light of recent developments in Jordan-Syria relations, should an opportunity arise to revise the current Yarmouk Agreement, what key modifications would you recommend?', 'في ضوء التطورات الأخيرة في العلاقات الأردنية السورية، وفي حال أُتيحت الفرصة لتعديل اتفاقية اليرموك الحالية، ما هي التعديلات الأساسية التي توصي بها؟', FALSE, NULL::nationality_type[]),
  ('Q4', 4, 'The 1987 Agreement focuses entirely on water allocation and does not address environmental protection in any form — such as environmental impact assessment, minimum ecological flows, or water quality standards. How has this absence shaped the environmental condition of the Yarmouk basin over the past four decades — and what specific environmental provisions would you consider essential in any future agreement?', 'تركّز اتفاقية 1987 بالكامل على تخصيص المياه ولا تتناول حماية البيئة بأي شكل — كتقييم الأثر البيئي أو الحد الأدنى للتدفقات البيئية أو معايير جودة المياه. كيف أثّر هذا الغياب على الوضع البيئي لحوض اليرموك خلال العقود الأربعة الماضية — وما هي الأحكام البيئية المحددة التي تعتبرها ضرورية في أي اتفاقية مستقبلية؟', FALSE, NULL::nationality_type[]),
  ('Q5', 5, 'What has your organization learned from supporting transboundary water cooperation in the Yarmouk basin or similar contexts? What worked and what didn''t?', 'ما هي الدروس المستفادة من دعمكم للتعاون المائي العابر للحدود في حوض اليرموك أو سياقات مشابهة؟ ما الذي نجح وما الذي لم ينجح؟', FALSE, NULL::nationality_type[]),
  ('Q6', 6, 'From your experience across multiple basins, what are the essential institutional features that make a transboundary water agreement actually work in practice?', 'من خبرتكم في أحواض متعددة، ما هي السمات المؤسسية الأساسية التي تجعل اتفاقية المياه العابرة للحدود تعمل فعلياً على أرض الواقع؟', FALSE, NULL::nationality_type[]),
  ('Q7', 7, 'What role can international organizations realistically play in supporting reform of the Yarmouk Agreement — technical assistance, mediation, financing, or capacity building?', 'ما هو الدور الذي يمكن للمنظمات الدولية أن تلعبه واقعياً في دعم إصلاح اتفاقية اليرموك — مساعدة فنية، وساطة، تمويل، أو بناء قدرات؟', FALSE, NULL::nationality_type[]),
  ('Q8', 8, 'Multiple international initiatives are now active on the Yarmouk basin simultaneously. How can these efforts be coordinated to avoid duplication and maximize impact?', 'تنشط حالياً عدة مبادرات دولية في حوض اليرموك في آن واحد. كيف يمكن تنسيق هذه الجهود لتجنب الازدواجية وتحقيق أقصى أثر؟', FALSE, NULL::nationality_type[]),
  ('Q9', 9, 'Is there anything else you would like to share regarding the 1987 Agreement, the environmental status of the Yarmouk basin, or the future of transboundary cooperation?', 'هل هناك أي شيء آخر تودّ مشاركته بخصوص اتفاقية 1987، أو الوضع البيئي لحوض اليرموك، أو مستقبل التعاون العابر للحدود؟', FALSE, NULL::nationality_type[]),
  ('F1', 10, 'Were any questions unclear or difficult to understand?', 'هل كانت أي من الأسئلة غير واضحة أو صعبة الفهم؟', TRUE, NULL::nationality_type[]),
  ('F2', 11, 'Were any questions too long?', 'هل كانت أي من الأسئلة طويلة جداً؟', TRUE, NULL::nationality_type[]),
  ('F3', 12, 'Was any important topic missing from the questions?', 'هل كان هناك أي موضوع مهم مفقود من الأسئلة؟', TRUE, NULL::nationality_type[]),
  ('F4', 13, 'How long did it take you to complete all questions?', 'كم من الوقت استغرقت للإجابة على جميع الأسئلة؟', TRUE, NULL::nationality_type[])
) AS d(question_code, order_index, text_en, text_ar, is_feedback, visible_nationalities);

-- ----- pilot_ngos: 13 questions -----
INSERT INTO questions (version_id, question_code, order_index, text_en, text_ar, is_feedback, is_required, visible_nationalities)
SELECT ver.id, d.question_code, d.order_index, d.text_en, d.text_ar, d.is_feedback, TRUE, d.visible_nationalities
FROM (SELECT id FROM questionnaire_versions WHERE variant = 'pilot_ngos') AS ver
CROSS JOIN (VALUES
  ('Q1', 1, 'How would you assess the overall performance of the 1987 Yarmouk Agreement in managing the shared water resources of the basin?', 'كيف تُقيّم الأداء العام لاتفاقية اليرموك لعام 1987 في إدارة الموارد المائية المشتركة للحوض؟', FALSE, NULL::nationality_type[]),
  ('Q2', 2, 'The Yarmouk River''s flow has declined significantly over the past decades. In your opinion, what are the main reasons for this decline — and to what extent has this decline affected the river''s ecosystem and surrounding environment?', 'شهد تدفق نهر اليرموك انخفاضاً ملحوظاً خلال العقود الماضية. برأيك، ما هي الأسباب الرئيسية لهذا الانخفاض — وإلى أي مدى أثّر هذا الانخفاض على النظام البيئي للنهر والبيئة المحيطة؟', FALSE, NULL::nationality_type[]),
  ('Q3', 3, 'In light of recent developments in Jordan-Syria relations, should an opportunity arise to revise the current Yarmouk Agreement, what key modifications would you recommend?', 'في ضوء التطورات الأخيرة في العلاقات الأردنية السورية، وفي حال أُتيحت الفرصة لتعديل اتفاقية اليرموك الحالية، ما هي التعديلات الأساسية التي توصي بها؟', FALSE, NULL::nationality_type[]),
  ('Q4', 4, 'The 1987 Agreement focuses entirely on water allocation and does not address environmental protection in any form — such as environmental impact assessment, minimum ecological flows, or water quality standards. How has this absence shaped the environmental condition of the Yarmouk basin over the past four decades — and what specific environmental provisions would you consider essential in any future agreement?', 'تركّز اتفاقية 1987 بالكامل على تخصيص المياه ولا تتناول حماية البيئة بأي شكل — كتقييم الأثر البيئي أو الحد الأدنى للتدفقات البيئية أو معايير جودة المياه. كيف أثّر هذا الغياب على الوضع البيئي لحوض اليرموك خلال العقود الأربعة الماضية — وما هي الأحكام البيئية المحددة التي تعتبرها ضرورية في أي اتفاقية مستقبلية؟', FALSE, NULL::nationality_type[]),
  ('Q5', 5, 'From your fieldwork and community engagement, what environmental changes have local residents and farmers reported in the Yarmouk basin — and how do these on-the-ground observations compare with official assessments of the basin''s environmental condition?', 'من خلال عملكم الميداني وتواصلكم مع المجتمعات المحلية، ما هي التغيرات البيئية التي أبلغ عنها السكان المحليون والمزارعون في حوض اليرموك — وكيف تقارن هذه الملاحظات الميدانية مع التقييمات الرسمية للوضع البيئي في الحوض؟', FALSE, NULL::nationality_type[]),
  ('Q6', 6, 'How are local communities along the Yarmouk affected by the decline in river flow, and what coping mechanisms have emerged?', 'كيف تتأثر المجتمعات المحلية على طول اليرموك بانخفاض تدفق النهر، وما هي آليات التكيف التي ظهرت؟', FALSE, NULL::nationality_type[]),
  ('Q7', 7, 'Are civil society organizations consulted or involved in any way in decisions about water sharing or the implementation of the 1987 Agreement?', 'هل تتم استشارة منظمات المجتمع المدني أو إشراكها بأي شكل في القرارات المتعلقة بتقاسم المياه أو تنفيذ اتفاقية 1987؟', FALSE, NULL::nationality_type[]),
  ('Q8', 8, 'What role should civil society and environmental organizations play in monitoring and enforcing environmental provisions in any future Yarmouk agreement — and are there examples from other basins where NGO involvement improved environmental outcomes?', 'ما هو الدور الذي ينبغي أن تلعبه منظمات المجتمع المدني والمنظمات البيئية في رصد وإنفاذ الأحكام البيئية في أي اتفاقية مستقبلية لليرموك — وهل هناك أمثلة من أحواض أخرى أدى فيها إشراك المنظمات غير الحكومية إلى تحسين النتائج البيئية؟', FALSE, NULL::nationality_type[]),
  ('Q9', 9, 'Is there anything else you would like to share regarding the 1987 Agreement, the environmental status of the Yarmouk basin, or the future of transboundary cooperation?', 'هل هناك أي شيء آخر تودّ مشاركته بخصوص اتفاقية 1987، أو الوضع البيئي لحوض اليرموك، أو مستقبل التعاون العابر للحدود؟', FALSE, NULL::nationality_type[]),
  ('F1', 10, 'Were any questions unclear or difficult to understand?', 'هل كانت أي من الأسئلة غير واضحة أو صعبة الفهم؟', TRUE, NULL::nationality_type[]),
  ('F2', 11, 'Were any questions too long?', 'هل كانت أي من الأسئلة طويلة جداً؟', TRUE, NULL::nationality_type[]),
  ('F3', 12, 'Was any important topic missing from the questions?', 'هل كان هناك أي موضوع مهم مفقود من الأسئلة؟', TRUE, NULL::nationality_type[]),
  ('F4', 13, 'How long did it take you to complete all questions?', 'كم من الوقت استغرقت للإجابة على جميع الأسئلة؟', TRUE, NULL::nationality_type[])
) AS d(question_code, order_index, text_en, text_ar, is_feedback, visible_nationalities);
